#!/bin/bash

case "$1" in
	lock)
        betterlockscreen -l
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        playerctl pause
        betterlockscreen -s
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
